# Generated by Django 6.0.3 on 2026-04-01 09:55

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('ticket_type', models.CharField(choices=[('capacity', 'Capacity Overload'), ('compliance', 'Compliance Report'), ('general', 'General Issue'), ('tech', 'Technical / Infrastructure')], db_index=True, max_length=20)),
                ('title', models.CharField(max_length=500)),
                ('description', models.TextField()),
                ('task_snapshot', models.JSONField(blank=True, help_text="Auto-captured snapshot of employee's current tasks. Only populated for CAPACITY tickets.", null=True)),
                ('status', models.CharField(choices=[('open', 'Open'), ('in_review', 'In Review'), ('resolved', 'Resolved')], db_index=True, default='open', max_length=20)),
                ('resolution_note', models.TextField(blank=True, help_text='How the issue was resolved. Required when resolving.', null=True)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('assigned_to', models.ForeignKey(blank=True, help_text='Auto-assigned based on ticket type routing rules.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_tickets', to=settings.AUTH_USER_MODEL)),
                ('created_by', models.ForeignKey(help_text='The employee who raised this ticket.', on_delete=django.db.models.deletion.CASCADE, related_name='created_tickets', to=settings.AUTH_USER_MODEL)),
                ('resolved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='resolved_tickets', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'tickets',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['assigned_to', 'status'], name='tickets_assigne_fc2b2b_idx')],
            },
        ),
    ]
