from django.contrib import admin

from .models import PerformanceSnapshot, PerformanceWeightConfig


@admin.register(PerformanceWeightConfig)
class PerformanceWeightConfigAdmin(admin.ModelAdmin):
    """Admin for the scoring weights singleton — one row per tenant."""

    list_display = [
        "weight_attendance",
        "weight_delivery",
        "weight_quality",
        "weight_reliability",
    ]


@admin.register(PerformanceSnapshot)
class PerformanceSnapshotAdmin(admin.ModelAdmin):
    """
    Admin for frozen performance snapshots.

    All fields are read-only because snapshots are generated by Celery,
    not by manual edits.  Admins can view and filter but not change.
    """

    list_display = [
        "employee",
        "period_type",
        "period_start",
        "overall_score",
        "rank",
    ]
    list_filter = ["period_type", "period_start"]
    search_fields = ["employee__email", "employee__first_name"]
    readonly_fields = [
        "employee",
        "period_type",
        "period_start",
        "period_end",
        "attendance_score",
        "delivery_score",
        "quality_score",
        "reliability_score",
        "overall_score",
        "rank",
        "total_ranked",
        "weights_used",
    ]
