# Generated by Django 6.0.3 on 2026-03-30 05:13

import uuid

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="LeaveRequest",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "leave_type",
                    models.CharField(
                        choices=[("full_day", "Full Day"), ("half_day", "Half Day")],
                        default="full_day",
                        max_length=20,
                    ),
                ),
                ("start_date", models.DateField()),
                ("end_date", models.DateField()),
                ("reason", models.TextField()),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending Team Lead Approval"),
                            ("tl_approved", "Approved by Team Lead"),
                            ("approved", "Fully Approved (HR)"),
                            ("rejected", "Rejected"),
                        ],
                        db_index=True,
                        default="pending",
                        max_length=20,
                    ),
                ),
                (
                    "review_remarks",
                    models.TextField(
                        blank=True, help_text="Final comments from reviewers.", null=True
                    ),
                ),
                (
                    "employee",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="leave_requests",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "hr_reviewer",
                    models.ForeignKey(
                        blank=True,
                        help_text="The HR manager who gave final system approval.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="hr_reviewed_leaves",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "tl_reviewer",
                    models.ForeignKey(
                        blank=True,
                        help_text="The Team Lead who first cleared the leave.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="tl_reviewed_leaves",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "leave_requests",
                "ordering": ["-created_at"],
            },
        ),
    ]
