# Generated by Django 6.0.3 on 2026-03-30 09:14

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("leaves", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="leaverequest",
            name="review_remarks",
        ),
        migrations.AddField(
            model_name="leaverequest",
            name="hr_comment",
            field=models.TextField(blank=True, help_text="Comments from HR.", null=True),
        ),
        migrations.AddField(
            model_name="leaverequest",
            name="is_half_day",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="leaverequest",
            name="tl_comment",
            field=models.TextField(blank=True, help_text="Comments from the Team Lead.", null=True),
        ),
        migrations.AddField(
            model_name="leaverequest",
            name="total_days",
            field=models.DecimalField(
                decimal_places=1,
                default=0.0,
                help_text="Calculated duration. 0.5 for half days.",
                max_digits=4,
            ),
        ),
        migrations.AlterField(
            model_name="leaverequest",
            name="leave_type",
            field=models.CharField(
                choices=[
                    ("sick", "Sick Leave"),
                    ("casual", "Casual Leave"),
                    ("earned", "Earned Leave"),
                    ("unpaid", "Unpaid Leave"),
                ],
                default="casual",
                max_length=20,
            ),
        ),
    ]
