# Generated by Django 6.0.3 on 2026-03-19 05:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("leaves", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name="leaverequest",
            name="reviewed_by",
        ),
        migrations.AddField(
            model_name="leaverequest",
            name="hr_reviewer",
            field=models.ForeignKey(
                blank=True,
                help_text="The HR manager who gave final system approval.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="hr_reviewed_leaves",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="leaverequest",
            name="tl_reviewer",
            field=models.ForeignKey(
                blank=True,
                help_text="The Team Lead who first cleared the leave.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="tl_reviewed_leaves",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="leaverequest",
            name="review_remarks",
            field=models.TextField(
                blank=True, help_text="Final comments from reviewers.", null=True
            ),
        ),
        migrations.AlterField(
            model_name="leaverequest",
            name="status",
            field=models.CharField(
                choices=[
                    ("pending", "Pending Team Lead Approval"),
                    ("tl_approved", "Approved by Team Lead"),
                    ("approved", "Fully Approved (HR)"),
                    ("rejected", "Rejected"),
                ],
                db_index=True,
                default="pending",
                max_length=20,
            ),
        ),
    ]
