# Generated by Django 5.2.12 on 2026-04-20 07:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0002_alter_client_schema_name_alter_domain_domain_and_more'),
        ('leaves', '0002_remove_leaverequest_review_remarks_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='leaverequest',
            name='tenant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='clients.client'),
        ),
    ]
