# Generated by Django 5.2.12 on 2026-04-24 06:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('leaves', '0003_leaverequest_tenant'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='leaverequest',
            name='tenant',
        ),
    ]
