# Generated by Django 5.2.12 on 2026-04-26 14:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0003_alter_client_schema_name_alter_domain_domain_and_more'),
        ('leaves', '0004_remove_leaverequest_tenant'),
    ]

    operations = [
        migrations.AddField(
            model_name='leaverequest',
            name='tenant',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='leave_requests', to='clients.client'),
        ),
    ]
