# Generated by Django 6.0.3 on 2026-04-24 08:45

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='WorkingReport',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('report_id', models.CharField(db_index=True, help_text='Unique identifier for the report, e.g., WR20240424143000', max_length=50, unique=True)),
                ('generated_at', models.DateTimeField(auto_now_add=True)),
                ('data', models.JSONField(default=list, help_text='A JSON array containing the snapshot of working records for each employee.')),
            ],
            options={
                'db_table': 'reports_working_reports',
                'ordering': ['-generated_at'],
            },
        ),
    ]
