# Generated by Django 5.2.12 on 2026-04-28 02:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='workingreport',
            name='date_from',
            field=models.DateField(blank=True, help_text='Start date of the range (only set for range reports).', null=True),
        ),
        migrations.AddField(
            model_name='workingreport',
            name='date_to',
            field=models.DateField(blank=True, help_text='End date of the range (only set for range reports).', null=True),
        ),
        migrations.AddField(
            model_name='workingreport',
            name='report_type',
            field=models.CharField(choices=[('daily', 'Daily Snapshot'), ('range', 'Date Range Report')], default='daily', help_text='Whether this is a single-day snapshot or a date-range report.', max_length=10),
        ),
        migrations.AlterField(
            model_name='workingreport',
            name='report_id',
            field=models.CharField(db_index=True, help_text='Unique identifier, e.g. WR20240424143000 or WRR20260428_20260421-20260428', max_length=80, unique=True),
        ),
    ]
