# Generated by Django 5.2.12 on 2026-04-28 02:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0003_alter_client_schema_name_alter_domain_domain_and_more'),
        ('reports', '0002_workingreport_date_from_workingreport_date_to_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='workingreport',
            name='tenant',
            field=models.ForeignKey(blank=True, help_text='The organisation this report belongs to.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='working_reports', to='clients.client'),
        ),
    ]
