# Generated by Django 6.0.3 on 2026-03-30 08:58

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("projects", "0001_initial"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Client",
            new_name="ExternalClient",
        ),
        migrations.AlterModelOptions(
            name="externalclient",
            options={"verbose_name": "External Client"},
        ),
        migrations.AddField(
            model_name="task",
            name="completion_pct",
            field=models.SmallIntegerField(
                default=0,
                help_text="Completion percentage 0–100. Updated by the assignee.",
                validators=[
                    django.core.validators.MinValueValidator(0),
                    django.core.validators.MaxValueValidator(100),
                ],
            ),
        ),
        migrations.AddField(
            model_name="task",
            name="complexity",
            field=models.SmallIntegerField(
                default=1,
                help_text="Difficulty rating 1–10. Set by TL at task creation.",
                validators=[
                    django.core.validators.MinValueValidator(1),
                    django.core.validators.MaxValueValidator(10),
                ],
            ),
        ),
        migrations.AddField(
            model_name="task",
            name="complexity_locked",
            field=models.BooleanField(
                default=False, help_text="Once True, complexity can never be changed."
            ),
        ),
        migrations.AddField(
            model_name="task",
            name="complexity_locked_at",
            field=models.DateTimeField(
                blank=True, help_text="Timestamp of when complexity was locked.", null=True
            ),
        ),
        migrations.AlterModelTable(
            name="externalclient",
            table="projects_client",
        ),
    ]
