# Generated by Django 5.2.12 on 2026-04-06 05:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_rename_client_externalclient_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='status',
            field=models.CharField(choices=[('open', 'Open'), ('progress', 'In Progress'), ('review', 'In Review'), ('rework', 'Rework'), ('closed', 'Closed')], db_index=True, default='open', max_length=20),
        ),
    ]
