# Generated by Django 6.0.3 on 2026-04-17 09:30

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("projects", "0002_rename_client_externalclient_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="task",
            name="actual_hours",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text="Actual hours spent, aggregated automatically from daily logs.",
                max_digits=6,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="task",
            name="estimated_hours",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text="Estimated hours to complete this task. Input by TL.",
                max_digits=6,
                null=True,
            ),
        ),
    ]
