# Generated by Django 6.0.3 on 2026-04-22 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0003_task_actual_hours_task_estimated_hours'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='delay_notes',
            field=models.TextField(blank=True, default='', help_text="Manager's explanation for why this project exceeded the target end date."),
        ),
    ]
