# Generated by Django 5.2.12 on 2026-04-17 03:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0001_initial'),
        ('projects', '0003_alter_task_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='department',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='services', to='organization.department'),
        ),
        migrations.AlterField(
            model_name='task',
            name='status',
            field=models.CharField(choices=[('open', 'Open'), ('progress', 'In Progress'), ('resolved', 'Resolved')], db_index=True, default='open', max_length=20),
        ),
    ]
