# Generated by Django 5.2.12 on 2026-04-20 06:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0002_alter_client_schema_name_alter_domain_domain_and_more'),
        ('projects', '0005_project_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='externalclient',
            name='tenant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='clients.client'),
        ),
        migrations.AddField(
            model_name='project',
            name='tenant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='clients.client'),
        ),
        migrations.AddField(
            model_name='service',
            name='tenant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='clients.client'),
        ),
        migrations.AlterField(
            model_name='externalclient',
            name='name',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='service',
            name='name',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterUniqueTogether(
            name='externalclient',
            unique_together={('name', 'tenant')},
        ),
        migrations.AlterUniqueTogether(
            name='service',
            unique_together={('name', 'tenant')},
        ),
    ]
