# Generated by Django 5.2.12 on 2026-04-20 08:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0002_department_tenant_designation_tenant_and_more'),
        ('projects', '0006_externalclient_tenant_project_tenant_service_tenant_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='owning_department',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='projects', to='organization.department'),
        ),
    ]
