# Generated by Django 5.2.12 on 2026-04-24 03:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0004_project_delay_notes'),
        ('projects', '0007_alter_project_owning_department'),
    ]

    operations = [
    ]
