# Generated by Django 5.2.12 on 2026-04-24 06:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0003_alter_client_schema_name_alter_domain_domain_and_more'),
        ('organization', '0003_alter_department_unique_together_and_more'),
        ('projects', '0008_merge_20260424_0916'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='externalclient',
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name='service',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='project',
            name='description',
        ),
        migrations.AlterField(
            model_name='externalclient',
            name='name',
            field=models.CharField(max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='externalclient',
            name='tenant',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='external_clients', to='clients.client'),
        ),
        migrations.AlterField(
            model_name='project',
            name='owning_department',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='projects', to='organization.department'),
        ),
        migrations.AlterField(
            model_name='project',
            name='tenant',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='projects', to='clients.client'),
        ),
        migrations.AlterField(
            model_name='service',
            name='department',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='services', to='organization.department'),
        ),
        migrations.AlterField(
            model_name='service',
            name='name',
            field=models.CharField(max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='service',
            name='tenant',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='services', to='clients.client'),
        ),
    ]
