# Generated by Django 5.2.12 on 2026-04-10 03:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0002_broadcast_broadcastacknowledgment'),
    ]

    operations = [
        migrations.AddField(
            model_name='broadcast',
            name='expiry_date',
            field=models.DateField(blank=True, help_text='Optional date after which the broadcast is considered expired.', null=True),
        ),
    ]
