# Generated by Django 5.2.12 on 2026-04-20 06:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0003_broadcast_expiry_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='broadcast',
            name='expiry_date',
        ),
    ]
