# Generated by Django 5.2.12 on 2026-04-24 06:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0005_broadcast_tenant_notification_tenant'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='broadcast',
            name='tenant',
        ),
        migrations.RemoveField(
            model_name='notification',
            name='tenant',
        ),
    ]
