# Generated by Django 6.0.3 on 2026-04-17 08:13

import uuid

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="PerformanceWeightConfig",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "weight_attendance",
                    models.DecimalField(
                        decimal_places=2,
                        default=0.2,
                        help_text="How much attendance matters (0.00–1.00).",
                        max_digits=3,
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(1),
                        ],
                    ),
                ),
                (
                    "weight_delivery",
                    models.DecimalField(
                        decimal_places=2,
                        default=0.35,
                        help_text="How much on-time task delivery matters (0.00–1.00).",
                        max_digits=3,
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(1),
                        ],
                    ),
                ),
                (
                    "weight_quality",
                    models.DecimalField(
                        decimal_places=2,
                        default=0.25,
                        help_text="How much complexity-weighted quality matters (0.00–1.00).",
                        max_digits=3,
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(1),
                        ],
                    ),
                ),
                (
                    "weight_reliability",
                    models.DecimalField(
                        decimal_places=2,
                        default=0.2,
                        help_text="How much daily log outcome reliability matters (0.00–1.00).",
                        max_digits=3,
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(1),
                        ],
                    ),
                ),
            ],
            options={
                "verbose_name": "Performance Config",
                "db_table": "performance_config",
            },
        ),
        migrations.CreateModel(
            name="PerformanceSnapshot",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "period_type",
                    models.CharField(
                        choices=[("weekly", "Weekly"), ("monthly", "Monthly")],
                        db_index=True,
                        max_length=10,
                    ),
                ),
                ("period_start", models.DateField(db_index=True)),
                ("period_end", models.DateField()),
                ("attendance_score", models.DecimalField(decimal_places=2, max_digits=5)),
                ("delivery_score", models.DecimalField(decimal_places=2, max_digits=5)),
                ("quality_score", models.DecimalField(decimal_places=2, max_digits=5)),
                ("reliability_score", models.DecimalField(decimal_places=2, max_digits=5)),
                (
                    "overall_score",
                    models.DecimalField(db_index=True, decimal_places=2, max_digits=5),
                ),
                ("rank", models.PositiveIntegerField(blank=True, null=True)),
                ("total_ranked", models.PositiveIntegerField(blank=True, null=True)),
                (
                    "weights_used",
                    models.JSONField(help_text="Snapshot of weight config at generation time"),
                ),
                (
                    "employee",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="performance_snapshots",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "performance_snapshots",
                "ordering": ["-period_start"],
                "indexes": [
                    models.Index(
                        fields=["period_type", "period_start", "overall_score"],
                        name="performance_period__6cbf0d_idx",
                    )
                ],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("employee", "period_type", "period_start"),
                        name="unique_performance_snapshot",
                    )
                ],
            },
        ),
    ]
