# Generated by Django 6.0.3 on 2026-03-13 09:11

import uuid

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="DailyLog",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("date", models.DateField(db_index=True, default=django.utils.timezone.now)),
                (
                    "morning_intent",
                    models.TextField(
                        blank=True,
                        help_text="What the employee plans to accomplish today.",
                        null=True,
                    ),
                ),
                ("clock_in_time", models.DateTimeField(blank=True, null=True)),
                (
                    "evening_summary",
                    models.TextField(
                        blank=True, help_text="What was actually completed.", null=True
                    ),
                ),
                ("clock_out_time", models.DateTimeField(blank=True, null=True)),
                (
                    "employee",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="daily_logs",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "attendance_daily_logs",
                "ordering": ["-date", "-created_at"],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("employee", "date"), name="unique_daily_log_per_employee"
                    )
                ],
            },
        ),
    ]
