# Generated by Django 6.0.3 on 2026-03-30 08:58

import uuid

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("attendance", "0001_initial"),
        ("projects", "0002_rename_client_externalclient_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="DailyLogEntry",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "custom_label",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="Used when no project is selected. E.g., 'Team Meetings', 'Code Review'.",
                        max_length=255,
                    ),
                ),
                (
                    "intent_text",
                    models.TextField(
                        help_text="What the employee plans to accomplish on this project today."
                    ),
                ),
                (
                    "output_text",
                    models.TextField(
                        blank=True,
                        default="",
                        help_text="What was actually accomplished. Filled during clock-out.",
                    ),
                ),
                (
                    "outcome",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("completed", "Completed as planned"),
                            ("partial", "Partially completed"),
                            ("blocked", "Blocked by dependency"),
                            ("carried_over", "Carried over to tomorrow"),
                            ("not_started", "Not started"),
                        ],
                        default="",
                        help_text="How did this work item end up? Set during clock-out.",
                        max_length=20,
                    ),
                ),
                (
                    "priority_order",
                    models.PositiveSmallIntegerField(
                        default=0, help_text="Display order. Lower number = higher priority."
                    ),
                ),
            ],
            options={
                "db_table": "attendance_daily_log_entries",
                "ordering": ["priority_order", "created_at"],
            },
        ),
        migrations.AddField(
            model_name="dailylog",
            name="general_notes",
            field=models.TextField(
                blank=True,
                default="",
                help_text="Optional free-text for non-project activities like meetings, training, etc.",
            ),
        ),
        migrations.AddField(
            model_name="dailylog",
            name="is_late",
            field=models.BooleanField(
                default=False,
                help_text="Auto-set to True if clock-in is after the org's threshold.",
            ),
        ),
        migrations.AddField(
            model_name="dailylog",
            name="status",
            field=models.CharField(
                choices=[
                    ("pending", "Pending"),
                    ("clocked_in", "Clocked In"),
                    ("clocked_out", "Clocked Out"),
                    ("missing", "Missing"),
                ],
                db_index=True,
                default="pending",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="dailylog",
            name="total_hours",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text="Hours worked, computed at clock-out.",
                max_digits=5,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="dailylog",
            name="evening_summary",
            field=models.TextField(
                blank=True,
                help_text="[LEGACY] Plain-text summary. New data uses DailyLogEntry instead.",
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="dailylog",
            name="morning_intent",
            field=models.TextField(
                blank=True,
                help_text="[LEGACY] Plain-text intent. New data uses DailyLogEntry instead.",
                null=True,
            ),
        ),
        migrations.AddIndex(
            model_name="dailylog",
            index=models.Index(fields=["date", "status"], name="attendance__date_037577_idx"),
        ),
        migrations.AddField(
            model_name="dailylogentry",
            name="daily_log",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="entries",
                to="attendance.dailylog",
            ),
        ),
        migrations.AddField(
            model_name="dailylogentry",
            name="project",
            field=models.ForeignKey(
                blank=True,
                help_text="The project this work item is about. Leave blank for general/misc work.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="daily_log_entries",
                to="projects.project",
            ),
        ),
        migrations.AddIndex(
            model_name="dailylogentry",
            index=models.Index(
                fields=["daily_log", "project"], name="attendance__daily_l_434026_idx"
            ),
        ),
    ]
