# Generated by Django 6.0.3 on 2026-04-17 09:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("attendance", "0002_dailylogentry_dailylog_general_notes_and_more"),
        ("projects", "0003_task_actual_hours_task_estimated_hours"),
    ]

    operations = [
        migrations.AddField(
            model_name="dailylogentry",
            name="distributed_hours",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text="Auto-calculated: total_hours × (task_complexity / total_complexity). Not manually entered.",
                max_digits=5,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="dailylogentry",
            name="morning_confidence",
            field=models.PositiveSmallIntegerField(
                blank=True,
                help_text="Confidence level 1-5 regarding completing this intent.",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="dailylogentry",
            name="outcome_reason",
            field=models.CharField(
                blank=True,
                choices=[
                    ("dependency", "Blocked by dependency"),
                    ("requirements", "Requirement unclear"),
                    ("underestimated", "Task larger than estimated"),
                    ("priority_shift", "Shifted to higher priority"),
                    ("personal", "Personal reasons/fatigue"),
                ],
                default="",
                help_text="Why the outcome was partial or blocked. Set during clock-out.",
                max_length=50,
            ),
        ),
        migrations.AddField(
            model_name="dailylogentry",
            name="task",
            field=models.ForeignKey(
                blank=True,
                help_text="The specific task this entry belongs to.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="work_log_entries",
                to="projects.task",
            ),
        ),
    ]
