# Generated by Django 5.2.12 on 2026-04-24 03:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0003_dailylog_tenant'),
        ('attendance', '0003_dailylogentry_distributed_hours_and_more'),
    ]

    operations = [
    ]
