# Generated by Django 5.2.12 on 2026-04-24 06:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0004_merge_20260424_0916'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dailylog',
            name='tenant',
        ),
    ]
