# Generated by Django 5.2.12 on 2026-04-26 14:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0005_remove_dailylog_tenant'),
        ('clients', '0003_alter_client_schema_name_alter_domain_domain_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='dailylog',
            name='tenant',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='daily_logs', to='clients.client'),
        ),
        migrations.AddField(
            model_name='dailylogentry',
            name='tenant',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='daily_log_entries', to='clients.client'),
        ),
    ]
