# Generated by Django 5.2.12 on 2026-04-26 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0006_dailylog_tenant_dailylogentry_tenant'),
    ]

    operations = [
        migrations.AddField(
            model_name='dailylog',
            name='is_early_exit',
            field=models.BooleanField(default=False, help_text='Set to True if clock-out is before the office end time (5:30 PM).'),
        ),
    ]
