# Generated by Django 6.0.3 on 2026-03-30 09:14

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="LoginAttempt",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("email", models.EmailField(db_index=True, max_length=254)),
                ("attempted_at", models.DateTimeField(auto_now_add=True)),
                ("was_successful", models.BooleanField(default=False)),
            ],
            options={
                "verbose_name": "Login Attempt",
                "verbose_name_plural": "Login Attempts",
                "db_table": "login_attempts",
                "ordering": ["-attempted_at"],
            },
        ),
        migrations.AddField(
            model_name="employee",
            name="leave_balance",
            field=models.DecimalField(
                decimal_places=1,
                default=0.0,
                help_text="Total remaining leave days available.",
                max_digits=5,
            ),
        ),
    ]
