# Generated by Django 6.0.3 on 2026-04-13 06:26

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0002_loginattempt_employee_leave_balance"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="employee",
            name="leave_balance",
        ),
    ]
