# Generated by Django 5.2.12 on 2026-04-05 20:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_loginattempt_employee_leave_balance'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='leave_balance',
            field=models.DecimalField(decimal_places=1, default=15.0, help_text='Total remaining leave days available.', max_digits=5),
        ),
    ]
