# Generated by Django 5.2.12 on 2026-04-09 01:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_employee_leave_balance'),
    ]

    operations = [
        migrations.CreateModel(
            name='TalentTag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('category', models.CharField(blank=True, help_text='e.g. Technical, Creative, Management', max_length=50)),
            ],
            options={
                'verbose_name': 'Talent Tag',
                'verbose_name_plural': 'Talent Tags',
                'db_table': 'talent_tags',
            },
        ),
        migrations.AddField(
            model_name='employee',
            name='evaluated_talents',
            field=models.ManyToManyField(blank=True, help_text='Talents identified/evaluated by Team Leads.', related_name='employees_evaluated', to='accounts.talenttag'),
        ),
        migrations.AddField(
            model_name='employee',
            name='self_declared_talents',
            field=models.ManyToManyField(blank=True, help_text='Skills self-declared by the employee.', related_name='employees_declared', to='accounts.talenttag'),
        ),
    ]
