# Generated by Django 5.2.12 on 2026-04-16 14:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_remove_employee_leave_balance'),
        ('accounts', '0005_employee_date_of_birth_employee_gender'),
    ]

    operations = [
    ]
