# Generated by Django 5.2.12 on 2026-04-24 05:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_employee_tenant'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee',
            name='self_declared_talents',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='evaluated_talents',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='date_of_birth',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='gender',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='tenant',
        ),
        migrations.AddField(
            model_name='loginattempt',
            name='ip_address',
            field=models.GenericIPAddressField(blank=True, db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name='employee',
            name='phone',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.DeleteModel(
            name='TalentTag',
        ),
    ]
