# Generated by Django 5.2.12 on 2026-04-26 13:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_add_ip_address_to_loginattempt'),
        ('clients', '0003_alter_client_schema_name_alter_domain_domain_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='tenant',
            field=models.ForeignKey(blank=True, help_text='The organization this employee belongs to.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='employees', to='clients.client'),
        ),
    ]
