# Generated by Django 6.0.3 on 2026-04-17 07:10

import uuid

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("contenttypes", "0002_remove_content_type_name"),
        ("organization", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ActivityEvent",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "event_type",
                    models.CharField(
                        choices=[
                            ("clock_in", "Clocked In"),
                            ("clock_out", "Clocked Out"),
                            ("task_created", "Task Created"),
                            ("task_completed", "Task Completed"),
                            ("task_progress", "Task Progress Updated"),
                            ("leave_requested", "Leave Requested"),
                            ("leave_approved", "Leave Approved"),
                            ("leave_rejected", "Leave Rejected"),
                            ("ticket_created", "Ticket Created"),
                            ("ticket_resolved", "Ticket Resolved"),
                            ("employee_joined", "New Employee"),
                            ("project_created", "Project Created"),
                            ("project_completed", "Project Completed"),
                            ("broadcast_sent", "Broadcast Sent"),
                        ],
                        db_index=True,
                        max_length=30,
                    ),
                ),
                ("timestamp", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("title", models.CharField(max_length=255)),
                ("detail", models.TextField(blank=True, default="")),
                ("object_id", models.UUIDField(blank=True, null=True)),
                ("icon", models.CharField(blank=True, default="", max_length=10)),
                ("metadata", models.JSONField(blank=True, null=True)),
                (
                    "actor",
                    models.ForeignKey(
                        help_text="Employee who performed this action.",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="activity_events",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "content_type",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="contenttypes.contenttype",
                    ),
                ),
                (
                    "department",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="activity_events",
                        to="organization.department",
                    ),
                ),
            ],
            options={
                "db_table": "activity_events",
                "ordering": ["-timestamp"],
                "indexes": [
                    models.Index(
                        fields=["event_type", "timestamp"], name="activity_ev_event_t_775c25_idx"
                    ),
                    models.Index(
                        fields=["department", "timestamp"], name="activity_ev_departm_96bbe0_idx"
                    ),
                    models.Index(
                        fields=["actor", "timestamp"], name="activity_ev_actor_i_9ea211_idx"
                    ),
                ],
            },
        ),
    ]
