# Generated by Django 5.2.12 on 2026-04-26 14:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activity', '0001_initial'),
        ('clients', '0003_alter_client_schema_name_alter_domain_domain_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='activityevent',
            name='tenant',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='activity_events', to='clients.client'),
        ),
    ]
